version: '3'

services:

  backend :
    image: "batch-app"
    container_name: "backend"
    ports:
      - 8080:8080
    environment:
      - DB_NAME=test
      - DB_USER=root
      - DB_PASSWORD=root

  frontend :
    container_name: "batch-ui"
    build:
      ./frontend
    volumes:
    - './frontend:/usr/src/app'
    ports:
    - 4200:4200
    command:
      bash -c "npm install && ng serve"

  database :
    image : mysql
    container_name: "db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD : root