version: '3.8'

services:

  backend :
    container_name: "backend"
    build:
      ./spring-batch
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: always

  frontend :
    container_name: "batch-ui"
    build:
      ./frontend
    ports:
    - 4200:4200
#    depends_on:
#      - backend
    command:
      bash -c "npm install && ng serve --host 0.0.0.0"

  database :
    image : mysql
    container_name: "database"
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_DATABASE : test
      MYSQL_ROOT_PASSWORD : root